### ISSUE TITLE
Can't compile on xCode 10.1

### ISSUE THREAD

**Issue by hr147** [freenowtech/Sensor#1]
I have cloned the project and try to compile it on xcode 10.1 it will give me an error. please check the attached imaged
<img width="1383" alt="screenshot 2018-12-19 at 1 57 21 pm" src="https://user-images.githubusercontent.com/15008942/50281179-76f31080-0470-11e9-8304-3b5705ed9ae7.png">

i have removed the entire carthage folder and run 

`carthage update --platform iOS` this command too but still not working. 

please add configuration & startup guide in your ReadMe.

**Comment by ferranlala** [comment]
Hi @hr147 thanks for reporting the issue. We have already merged a fix to master.

**Comment by carlosnaguilera** [comment]
Thanks Ferran for the fix
